### ISSUE TITLE
How do I use the "StringMaker" with "TextMeshProUGUI"?

### ISSUE THREAD

**Issue by djzombie84** [swipetrack/switchboard#3]
I only did a mini test to get to know it but unfortunately I see a lot of GC ? in the profiler.
What am I doing wrong ?

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Switchboard;
using TMPro;

public class textConverterTest : MonoBehaviour
{
    public string text;
    public int zahl;
    private StringMaker StringMaker = StringMaker.Shared;
    public TextMeshProUGUI anzeige;
    public string formatString = "{0:F2}";

    // Start is called before the first frame update
    void Start()
    {
        StringMaker.Clear();
        zahl = 0;
    }

    // Update is called once per frame
    void Update()
    {
        StringMaker.Append(zahl);
        anzeige.SetText(StringMaker.ToString());
        text = StringMaker.ToString();
        zahl++;
        StringMaker.Clear();

    }
}

**Comment by moonymachine** [comment]
Thank you for trying Switchboard! I see a few issues with your first attempt that would definitely allocate garbage. However, thanks to your report I was forced to profile a matching example case, and I found an issue that will be fixed within 24 hours when I submit version 2.0.0.

First, any time you call StringMaker.ToString(), it will allocate garbage memory. There's no way to avoid that. When a new string is created, it generates garbage. But, if you can pass the contents of the StringMaker to the destination without calling ToString, you can fully avoid garbage allocation.

One reason that is an easy mistake to make is that the extension method I added to TextMeshPro is called SetText, which matches the SetText(string) method name. In the next version, that method will be called SetCharArray instead, so that mismatch of types will be obvious. You can change the name yourself in the TextMeshProExtensions file.

Speaking of TextMeshProExtensions, if you have not opened that file and uncommented the contents, you must do that to enable TextMesh Pro support. I include the extension methods there commented out, so that I do not have to include TextMesh Pro as a dependency of Switchboard when I submit to the Unity Asset Store. However, I have an improved version of the TextMeshProExtensions file that I am submitting with version 2, that you should just copy over your existing TextMeshProExtensions file.

Even I was seeing garbage in the profiler when I recreated your test on my end. However, I tracked the source of the allocations to TextMesh Pro's SetCharArray method. That is supposed to be their method that doesn't allocate garbage, but it was. However, I was reminded that you should always profile in a build, not the editor, for accurate results. So, I made a build, but there was still garbage, but not from SetCharArray! So, I put profiler samples around every line of code, remade the build, and discovered that the garbage was now coming a line of code in TextMeshProExtensions that compares the StringMaker to the TextMesh Pro text value to check if they are equal, before calling SetCharArray. Apparently, in a build, accessing that text property on TextMesh Pro allocates garbage, but not in the editor. It's all very weird, but in any case, I removed the condition that checks if the text is not equal before setting it. I had heard at some point in the past that it was a good thing to check, to avoid causing TextMesh Pro to rebuild character geometry, but I see now that it only leads to more garbage. So, thank you for the report!

Please copy the contents of this TextMeshProExtensions file over your existing file:
```csharp
using System;
using TMPro;

// Uncomment this class if using TextMeshPro to set text without allocating garbage, and to avoid updating text geometry if the text hasn't changed.
namespace Switchboard
{
	public static class TextMeshProExtensions
	{
		private const int StaticBufferLength = 32768;
		private static char[] StaticBuffer => Buffer ??= new char[StaticBufferLength];
		private static char[] Buffer;

		public static void SetCharArray(this TMP_Text textMeshPro, StringMaker stringMaker)
		{
			SetCharArray(textMeshPro, stringMaker, null);
		}

		public static void SetCharArray(this TMP_Text textMeshPro, StringMaker stringMaker, char[] buffer)
		{
			if(textMeshPro == null)
				ThrowArgumentNullException(nameof(textMeshPro));

			if(stringMaker == null)
				ThrowArgumentNullException(nameof(stringMaker));

			if(buffer != null)
			{
				if(buffer.Length < stringMaker.Length)
					ThrowArgumentException($"The character buffer is not long enough.", nameof(buffer));
			}
			else
			{
				buffer = (stringMaker.Length > StaticBufferLength) ? new char[stringMaker.Length] : StaticBuffer;
			}

			stringMaker.CopyTo(new Span<char>(buffer));
			textMeshPro.SetCharArray(buffer, 0, stringMaker.Length);
		}

		private static void ThrowArgumentNullException(string paramName) => throw new ArgumentNullException(paramName);
		private static void ThrowArgumentException(string message, string paramName) => throw new ArgumentException(message, paramName);
	}
}
```

And then, this example should allocate zero garbage when profiling an actual build of the game:
```csharp
using Switchboard;
using TMPro;
using UnityEngine;

public class Example : MonoBehaviour
{
	private int Zahl;
	private StringMaker StringMaker = StringMaker.Shared;
	public TextMeshProUGUI Anzeige;

	private void Update()
	{
		StringMaker.Clear().Append(Zahl);

		// Issue #1: Do not call StringMaker.ToString(), as it will always allocate garbage.
		// This method is soon to be renamed in version 2 to SetCharArray, so this type of error cannot happen.
		// Incorrect: Anzeige.SetText(StringMaker.ToString());
		// Correct:
		Anzeige.SetCharArray(StringMaker);
		// If you encounter a syntax error ^here, you must open the TextMeshProExtensions file in the Scripts folder,
		// and uncomment the contents of that file. If I included TextMesh Pro support directly, I would have to
		// specify a dependency on the TextMeshPro plugn to submit to the Asset Store.
		// But, the TextMeshProExtensions methods in previous versions have an equality comparison that allocates garbage.
		// Remove that condition or use the new version provided. Rename SetText to SetCharArray so no confusion can happen with ToString.

		// This will always allocate garbage, so it must be commented out to reach 0 GC.
		//Text = StringMaker.ToString();

		// StringMaker can only fully avoid garbage allocation by copying the contents of the StringMaker into the destination.
		// See the contents of TextMeshProExtensions to see how it allocates memory on the stack, and copies the StringMaker,
		// then sends that to TextMesh Pro's SetCharArray method.

		++Zahl;
	}
}
```

**Comment by moonymachine** [comment]
Also, version 2.0.0 has just released. So, if you just update to the latest version there is a TextMesh Pro example scene included now with all of this information.

**Comment by djzombie84** [comment]
Wow. Thanks for the quick reply ^^
I'll have a look at it straight away :)
Thanks for your help 

translate by Google

**Comment by djzombie84** [comment]
Works great :)

**Comment by moonymachine** [comment]
I'm glad everything is working as expected! If you like Switchboard, leaving a positive review on the Unity Asset Store would be so appreciated! Just let me know if you have any other questions or issues.
